name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to click a button to build manually if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # --- THE FIX ---
      # Since we are coding in the browser, we don't have the "gradlew" script.
      # This command forces the server to generate it for us before building.
      - name: Generate Gradle Wrapper
        run: gradle wrapper --gradle-version 8.0

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HapticAura-Debug
          path: app/build/outputs/apk/debug/app-debug.apk
